language: java

jdk:
  - oraclejdk8
deploy:
  provider: releases
    api_key:
      secure: "vyQ9B9V/xnpRhIM6PdLXgGZT4qR7b90pIW0IGB4GhgDqJhaN3Y0u7zfcqpkMAm7Ti0SqpvsMldYO3CCARMuKAso/kOmev+zfpVa1gJ76YXpns8LIcfNQksQQ/FV1FG/M9GWP/sfaA7CrC74JX05ZZ24HzVfhkK/b2jPtRKt1QniXnpqC/wtgl47KaBjRSdToNeHke8CNCNNuuMRFWX/vMRl9s8fRseCp2henLpchatro0H+qjiOUKwmFqdC7mDX0z/gSCOKeoy62R+P+PIU+J02lLannFxwHA8WspkzjuSCxIwj/a7sAJnH89OZi/X1CBMdoxTwHCUP3GFNc2G7B1hAnHIH0GhFaiXBsMVFORZbaWxalr0fqZh6zBBIEDu+0uGMiedqe8lF/gM9jEgB3HbaEepSyohXUFPl/G0Rzl7Yxf/oOxJtzf0znpG5rU3A7PJPmpMTFKA/cIMr142FSDTHgqeln2mDLA8kgSo0PcpZ+AvSKuuPk/u4+UGeCYouzKz4ljCoiEBhphD6cHRti5piNBzAg7WN6rE6RWmJBVL66njy2wg+WRLt9hLSRWaAucBSeL9e1l0YksT3PSTmBRnswgUBF0+jn8Oac3me1zd5ol64yaGleevqlbsn8nT/cLsy3/FAFeGk6DMN9xLJSKtr05S1Zbyx80mT84FxXl8w="
  file: 'release.zip'
  skip_cleanup: true
  on:
    tags: true
